name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
- name: Cache
  uses: actions/cache@v1.1.2
  with:
    # A directory to store and save the cache
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    restore-keys: # optional
    - name: Cachix
  uses: cachix/cachix-action@v5
  with:
    # Name of a cachix cache to push and pull/substitute
    name: 
    # Authentication token for Cachix, needed only for private cache access
    authToken: # optional
    # Signing key secret retrieved after creating binary cache on https://cachix.org
    signingKey: # optional
    # Set to true to not invoke nix-build after setup.
    skipNixBuild: # optional
    # Nix file to build. Defaults to default.nix
    file: # optional
    # Nix attributes to nix-build. By default, all attributes are built.
    attributes: # optional
    # Additional arguments for nix-build.
    nixBuildArgs: # optional
    - name: Always-Cache
  uses: gerbal/always-cache@v1.0.3
  with:
    # A directory to store and save the cache
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    restore-keys: # optional
    - name: markdown-link-check
  uses: gaurav-nelson/github-action-markdown-link-check@0.6.0
  with:
    # Use yes to enable markdown-link-check quiet mode which only list errors.
    use-quiet-mode: # default is no
    # Use yes to enable markdown-link-check verbose mode which lists additional details.
    use-verbose-mode: # default is no
    # Specify path to a markdown-link-check JSON configuration file.
    config-file: # default is mlc_config.json
    # Specify path to a custom folder where your markdown files are located.
    folder-path: # default is .
    - name: Link Checker
  uses: peter-evans/link-checker@v1.2.1
